GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/4

###

DELETE http://localhost:3001/api/persons/3

###
POST https://fullstackopen-6iji.onrender.com/api/persons
Content-Type: application/json

{
  "name": "riz2",
  "number": "23456789"
}